// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"fmt"
)

// Injectors from wire.go:

func InitializeBot() (Bot, error) {
	bot := NewBot()
	return bot, nil
}

// wire.go:

type Bot struct{}

func (b *Bot) Start() {
	fmt.Println("Hey")
}

func NewBot() Bot {
	return Bot{}
}
