// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/dfontana/disbot/pkg/bot"
)

// Injectors from wire.go:

func InitializeBot() (bot.Bot, error) {
	config, err := bot.NewConfig()
	if err != nil {
		return bot.Bot{}, err
	}
	botBot, err := bot.NewBot(config)
	if err != nil {
		return bot.Bot{}, err
	}
	return botBot, nil
}
