[package]
name = "disbot"
version = "0.1.0"
authors = ["dfontana <dyfontana@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["full"] }
serenity = {default-features = false,features = ["client", "cache", "gateway", "model","rustls_backend"],version = "0.10.2"}
