[package]
name = "disbot"
version = "0.1.0"
authors = ["dfontana <dyfontana@gmail.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.10.0"
dotenv = "0.15.0"
hex = "0.4.3"
humantime = "2.1.0"
lazy_static = "1.4.0"
openssl = { version = "0.10.35", features = ["vendored"] }
rand = "0.8.2"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
select = "0.5.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0"
serenity = {features = ["client", "cache", "gateway", "model","rustls_backend", "framework", "standard_framework", "voice"], git ="https://github.com/acdenisSK/serenity", branch="apple_quotes_args"}
songbird = {features = ["builtin-queue"], git = "https://github.com/dfontana/songbird"}
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
