[package]
name = "disbot"
version = "0.1.0"
authors = ["dfontana <dyfontana@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
rand = "0.8.2"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
select = "0.5.0"
serenity = {default-features = false, features = ["client", "cache", "gateway", "model","rustls_backend", "framework", "standard_framework"], version = "0.10.4"}
tokio = { version = "1.0", features = ["full"] }
