version: "3.8"
services:
  disbot:
    container_name: disbot
    build:
      context: .
      dockerfile: ./docker/disbot/Dockerfile
    image: disbot:latest
    env_file: 
      - ./docker/disbot/prod.env
    deploy:
      restart_policy:
        condition: on-failure
