version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      MEMORY: 5G
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Valhelsia+3-3.2.3-SERVER.zip
      CF_BASE_DIR: /data
    volumes:
      - ./modpacks:/modpacks:ro
      - ./valhelsia:/data
